import axios from "axios"
import { GetServerSideProps } from "next"
import Head from "next/head"
import { useEffect } from "react"
import { buildClient } from "../api/build-client"

interface HomeProps {
    user?: { id: string; username: string }
}

export default function Home({ user }: HomeProps) {
    useEffect(() => {}, [])
    function getCurrentUser() {
        const client = buildClient()
        client.get("/api/auth/current").then((res) => {
            console.log(res.data)
        })
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="">{user ? "Loggged In" : "Not logged in"}</div>
            <button
                className="btn btn-primary"
                onClick={() => getCurrentUser()}
            >
                Click to get current user
            </button>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
    ctx
) => {
    let user = null
    try {
        const client = buildClient(ctx)
        const { data } = await client.get("/api/auth/current")
        user = data
    } catch (error) {
        console.error(error.response.data)
    }
    console.log("HomePage", user)

    return {
        props: {
            user,
        },
    }
}
