import axios from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";

interface HomeProps {
  user?: { id: string; username: string };
}

export default function Home({ user }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">{user ? "Loggged In" : "Not logged in"}</div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async ({
  req,
}) => {
  let user = null;
  try {
    if (typeof window === "undefined") {
      const { data } = await axios.get(
        "http://localhost:5000/api/auth/current",
        {
          headers: req.headers,
        }
      );
      user = data;
      console.log("Server", data);
    } else {
      const { data } = await axios.get(
        "http://localhost:5000/api/auth/current"
      );
      user = data;
      console.log("Client", data);
    }
  } catch (error) {
    console.error(error.response.data);
  }

  return {
    props: {
      user,
    },
  };
};
