import axios from "axios"
import { GetServerSideProps } from "next"
import Head from "next/head"
import { buildClient } from "../src/api/build-client"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="">Hello World</div>
        </div>
    )
}
