### Sign Up User
POST http://localhost:5000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "test4@test.com",
    "password": "12345678",
    "username": "test4"
}


### Sign In User
POST http://localhost:5000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "test4@test.com",
    "password": "12345678"
}


### Sign Out
POST http://localhost:5000/api/auth/signout HTTP/1.1
Content-Type: application/json


### Fetch posts
GET http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

### Create Post
POST http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

{
    "description": "Scenery",
    "image": "https://images.pexels.com/photos/258109/pexels-photo-258109.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
}